### ISSUE TITLE
parties page items

### ISSUE THREAD

**Issue by navidzand131** [tcfev/Atlas#21]
at this page : https://atlas.transcf.org/parties 
we need to fix each the item 
![image](https://github.com/user-attachments/assets/3483124d-df2d-46ac-a1c3-b8aae2e14e17)

**Comment by navidzand131** [comment]
@next-free

**Comment by next-free** [comment]
> @next-free

what is the page url in the repository? the url not loading for me 
![image](https://github.com/user-attachments/assets/51cc6c25-dcc0-4615-8c71-637cea236858)

**Comment by armantorkzaban** [comment]
We have migrated to Atlasiran.org
Sorry for the delayed reply. @next-free

**Comment by next-free** [comment]
@armantorkzaban new repo or same repo?

**Comment by armantorkzaban** [comment]
We are still in the same repo, just a new web address.

**Comment by armantorkzaban** [comment]
@next-free @navidzand131 
The parties section does not work

**Comment by armantorkzaban** [comment]
I fixed the issue. Main is now updated with correst view of parties.

**Comment by armantorkzaban** [comment]
I fixed the issue. Main is now updated with correst view of parties.
