### ISSUE TITLE
empty groups

### ISSUE THREAD

**Issue by next-free** [tcfev/Atlas#23]
![image](https://github.com/user-attachments/assets/168f6210-7c52-4656-ac36-412adedab05e)
how can i delete this kind of groups in data.json file? just delete them, or make all data empty (like this item: "", ) or i must replace "null" ?

**Comment by armantorkzaban** [comment]
What is your suggestion? Do what is best.

**Comment by armantorkzaban** [comment]
I took care of this. Changes made should reflect this.

**Comment by next-free** [comment]
yes, data changed and shown correctly now
